### ISSUE TITLE
Provide summary of highest swaps per day/week [400 FLIP]

### ISSUE THREAD

**Issue by 0xSleipnir** [CumpsD/chainflip-insights#23]
# Provide summary of highest swaps per day/week

## Scope

Every day, announce the top swap.

Every week provide a summary of the 5 biggest swaps of that week. As well as the biggest all-time swap.

## More Info

```
Today's highest swap was X token to Y token
```

```
Weekly highest swaps from 0x.0x.20xx to 0x+1.0x+1.20xx
     A
     B
     C
     D
```

## Bounty

FLIP required for development: **400 FLIP**
To start development, send the bounty to **0x2578f4fa0f36138c76389095bf74331a4f57bcc0** and comment with a link to the transaction.

**Comment by 0xSleipnir** [comment]
Somehow the first line got eaten up for whatever reason.
Should be "Highest swap was X to Y".

**Comment by Haafingar** [comment]
I would do:
Weekly: top 5 swaps of the week, biggest all-time swap
Daily: top 5 swaps of the day

If that is the scope Chainflip labs will fund the bounty :)

**Comment by CumpsD** [comment]
https://etherscan.io/tx/0x558978922757ae30407258aee1eec00b2f6f9b280d9c2e74cf58eea0c805a6bc

**Comment by CumpsD** [comment]
Daily Overview:

Discord
![Image](https://github.com/user-attachments/assets/619d44c9-5606-460e-9ab3-df755a4e6cb7)

Telegram
![Image](https://github.com/user-attachments/assets/3499061b-23f2-4569-8a1f-c8f2fa4b2990)

Mastodon
![Image](https://github.com/user-attachments/assets/8edf1a3c-30d8-406e-8c13-7415b2bb346d)

Twitter hit a rate limit, so that will come later

**Comment by CumpsD** [comment]
Weekly overview of biggest swap per asset:

Discord
![Image](https://github.com/user-attachments/assets/d3fcc045-efe0-4630-bae3-e5a2f176ad47)

Telegram
![Image](https://github.com/user-attachments/assets/bbae07a5-4a4c-4587-8eff-b9ce90f57144)
